on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregyael.azurecr.io
        username: ${{ secrets.acr_containerregyael_username }}
        password: ${{ secrets.acr_containerregyael_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t containerregyael.azurecr.io/aksyael1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push containerregyael.azurecr.io/aksyael1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksyael1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo-yael | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo-yael`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo-yael
        container-registry-url: containerregyael.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregyael_username }}
        container-registry-password: ${{ secrets.acr_containerregyael_password }}
        secret-name: aksyael1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo-yael
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          containerregyael.azurecr.io/aksyael1:${{ github.sha }}
        imagepullsecrets: |
          aksyael1dockerauth
